"""Example data that matches the production.usr table schema."""

from datetime import datetime, timedelta

MOCK_USER_DATA = [
    {
        "usr_id": 1,
        "usr_first_name": "John",
        "usr_last_name": "Doe",
        "usr_email": "johndoe@example.com",
        "usr_password": "securepassword1",
        "usr_prefs": "{}",
        "usr_admin": 1,
        "usr_last_seen": datetime.now(),
        "usr_created": datetime.now().date(),
        "ip_addr": "192.168.0.1",
        "apikey": "apikey1",
        "is_guest": False,
        "usr_sso_id": "sso1",
    },
    {
        "usr_id": 2,
        "usr_first_name": "Jane",
        "usr_last_name": "Doe",
        "usr_email": "janedoe@example.com",
        "usr_password": "securepassword2",
        "usr_prefs": "{}",
        "usr_admin": 0,
        "usr_last_seen": datetime.now(),
        "usr_created": datetime.now().date(),
        "ip_addr": "192.168.0.2",
        "apikey": "apikey2",
        "is_guest": False,
        "usr_sso_id": "sso2",
    },
    {
        "usr_id": 3,
        "usr_first_name": "Alice",
        "usr_last_name": "Johnson",
        "usr_email": "alicejohnson@example.com",
        "usr_password": "securepassword3",
        "usr_prefs": "{}",
        "usr_admin": 2,
        "usr_last_seen": datetime.now() - timedelta(days=5),
        "usr_created": datetime.now().date() - timedelta(days=10),
        "ip_addr": "192.168.0.3",
        "apikey": "apikey3",
        "is_guest": False,
        "usr_sso_id": "sso3",
    },
    {
        "usr_id": 4,
        "usr_first_name": "Bob",
        "usr_last_name": "Smith",
        "usr_email": "bobsmith@example.com",
        "usr_password": "securepassword4",
        "usr_prefs": "{}",
        "usr_admin": 0,
        "usr_last_seen": datetime.now() - timedelta(days=2),
        "usr_created": datetime.now().date() - timedelta(days=30),
        "ip_addr": "192.168.0.4",
        "apikey": "apikey4",
        "is_guest": False,
        "usr_sso_id": "sso4",
    },
    {
        "usr_id": 5,
        "usr_first_name": "Charlie",
        "usr_last_name": "Brown",
        "usr_email": "charliebrown@example.com",
        "usr_password": "securepassword5",
        "usr_prefs": "{}",
        "usr_admin": 1,
        "usr_last_seen": datetime.now(),
        "usr_created": datetime.now().date() - timedelta(days=15),
        "ip_addr": "192.168.0.5",
        "apikey": "apikey5",
        "is_guest": True,
        "usr_sso_id": "sso5",
    },
]
