"""Constants for the publication unit tests."""

PUBMED_PUBLICATIONS = [
    (
        123456,
        {
            "pub_id": 1,
            "pub_authors": "Author1, Author2",
            "pub_title": "Title1",
            "pub_abstract": "Abstract1",
            "pub_journal": "Journal1",
            "pub_volume": "Volume1",
            "pub_pages": "Pages1",
            "pub_month": "Month1",
            "pub_year": "Year1",
            "pub_pubmed": "123456",
            "_searchtext": None,
        },
    ),
    (
        123457,
        {
            "pub_id": 2,
            "pub_authors": "Author3, Author4",
            "pub_title": "Title2",
            "pub_abstract": "Abstract2",
            "pub_journal": "Journal2",
            "pub_volume": "Volume2",
            "pub_pages": "Pages2",
            "pub_month": "Month2",
            "pub_year": "Year2",
            "pub_pubmed": "123457",
            "_searchtext": None,
        },
    ),
    (
        123458,
        {
            "pub_id": 3,
            "pub_authors": "Author5, Author6",
            "pub_title": "Title3",
            "pub_abstract": "Abstract3",
            "pub_journal": "Journal3",
            "pub_volume": "Volume3",
            "pub_pages": "Pages3",
            "pub_month": "Month3",
            "pub_year": "Year3",
            "pub_pubmed": "123458",
            "_searchtext": None,
        },
    ),
    (
        123459,
        {
            "pub_id": 4,
            "pub_authors": "Author7, Author8",
            "pub_title": "Title4",
            "pub_abstract": "Abstract4",
            "pub_journal": "Journal4",
            "pub_volume": "Volume4",
            "pub_pages": "Pages4",
            "pub_month": "Month4",
            "pub_year": "Year4",
            "pub_pubmed": "123459",
            "_searchtext": None,
        },
    ),
    (
        123460,
        {
            "pub_id": 5,
            "pub_authors": "Author9, Author10",
            "pub_title": "Title5",
            "pub_abstract": "Abstract5",
            "pub_journal": "Journal5",
            "pub_volume": "Volume5",
            "pub_pages": "Pages5",
            "pub_month": "Month5",
            "pub_year": "Year5",
            "pub_pubmed": "123460",
            "_searchtext": None,
        },
    ),
    (
        123461,
        {
            "pub_id": 6,
            "pub_authors": "Author11, Author12",
            "pub_title": "Title6",
            "pub_abstract": "Abstract6",
            "pub_journal": "Journal6",
            "pub_volume": "Volume6",
            "pub_pages": "Pages6",
            "pub_month": "Month6",
            "pub_year": "Year6",
            "pub_pubmed": "123461",
            "_searchtext": None,
        },
    ),
    (
        123462,
        {
            "pub_id": 7,
            "pub_authors": "Author13, Author14",
            "pub_title": "Title7",
            "pub_abstract": "Abstract7",
            "pub_journal": "Journal7",
            "pub_volume": "Volume7",
            "pub_pages": "Pages7",
            "pub_month": "Month7",
            "pub_year": "Year7",
            "pub_pubmed": "123462",
            "_searchtext": None,
        },
    ),
    (
        123463,
        {
            "pub_id": 8,
            "pub_authors": "Author15, Author16",
            "pub_title": "Title8",
            "pub_abstract": "Abstract8",
            "pub_journal": "Journal8",
            "pub_volume": "Volume8",
            "pub_pages": "Pages8",
            "pub_month": "Month8",
            "pub_year": "Year8",
            "pub_pubmed": "123463",
            "_searchtext": None,
        },
    ),
    (
        123464,
        {
            "pub_id": 9,
            "pub_authors": "Author17, Author18",
            "pub_title": "Title9",
            "pub_abstract": "Abstract9",
            "pub_journal": "Journal9",
            "pub_volume": "Volume9",
            "pub_pages": "Pages9",
            "pub_month": "Month9",
            "pub_year": "Year9",
            "pub_pubmed": "123464",
            "_searchtext": None,
        },
    ),
    (
        123474,
        {
            "pub_id": 19,
            "pub_authors": "Author37, Author38",
            "pub_title": "Title19",
            "pub_abstract": "Abstract19",
            "pub_journal": "Journal19",
            "pub_volume": "Volume19",
            "pub_pages": "Pages19",
            "pub_month": "Month19",
            "pub_year": "Year19",
            "pub_pubmed": "123474",
            "_searchtext": None,
        },
    ),
    (
        123475,
        {
            "pub_id": 20,
            "pub_authors": "Author39, Author40",
            "pub_title": "Title20",
            "pub_abstract": "Abstract20",
            "pub_journal": "Journal20",
            "pub_volume": "Volume20",
            "pub_pages": "Pages20",
            "pub_month": "Month20",
            "pub_year": "Year20",
            "pub_pubmed": "123475",
            "_searchtext": None,
        },
    ),
]

EDGE_CASE_PUBMED_PUBLICATIONS = [
    # Non-existance PMID
    (999999, None),
    (999998, None),
    (987654, None),
    (789012, None),
    (0, None),
    # Edge case: Empty title
    (
        123457,
        {
            "pub_id": 2,
            "pub_authors": "Author3, Author4",
            "pub_title": "",
            "pub_abstract": "Abstract2",
            "pub_journal": "Journal2",
            "pub_volume": "Volume2",
            "pub_pages": "Pages2",
            "pub_month": "Month2",
            "pub_year": "Year2",
            "pub_pubmed": "123457",
            "_searchtext": None,
        },
    ),
    # Edge case: No authors
    (
        123458,
        {
            "pub_id": 3,
            "pub_authors": "",
            "pub_title": "Title3",
            "pub_abstract": "Abstract3",
            "pub_journal": "Journal3",
            "pub_volume": "Volume3",
            "pub_pages": "Pages3",
            "pub_month": "Month3",
            "pub_year": "Year3",
            "pub_pubmed": "123458",
            "_searchtext": None,
        },
    ),
    # Edge case: No abstract
    (
        123459,
        {
            "pub_id": 4,
            "pub_authors": "Author7, Author8",
            "pub_title": "Title4",
            "pub_abstract": "",
            "pub_journal": "Journal4",
            "pub_volume": "Volume4",
            "pub_pages": "Pages4",
            "pub_month": "Month4",
            "pub_year": "Year4",
            "pub_pubmed": "123459",
            "_searchtext": None,
        },
    ),
    # Edge case: PMID is not an integer
    ("abcd", None),
]
