"""Constant test data for the geneset db module unit tests."""

GENESET_CURATION_IDS = [None, 1, 2, 3, 4, 5]

GENESETS = [
    {
        "gs_id": 10134,
        "usr_id": 51,
        "file_id": 0,
        "gs_name": "Test",
        "gs_abbreviation": "Test",
        "pub_id": None,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "Test",
        "sp_id": 1,
        "gs_count": 3,
        "gs_threshold_type": 1,
        "gs_threshold": 0.5,
        "gs_groups": -1,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": 13,
        "gs_created": "2009-03-20",
        "admin_flag": "empty_file_no_data",
        "gs_updated": "2009-03-20 00:00:00",
        "gs_status": "normal",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 225457,
        "usr_id": 7579395,
        "file_id": 279391,
        "gs_name": "151 ProbeSets imported from Genenetwork",
        "gs_abbreviation": "import from Genenetwork",
        "pub_id": None,
        "res_id": None,
        "cur_id": None,
        "gs_description": "151 ProbeSets imported from Genenetwork",
        "sp_id": 2,
        "gs_count": 1,
        "gs_threshold_type": 3,
        "gs_threshold": 0.5,
        "gs_groups": None,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -1,
        "gs_created": None,
        "admin_flag": None,
        "gs_updated": "2015-07-16 12:31:20.054835",
        "gs_status": "normal",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 355822,
        "usr_id": 563,
        "file_id": 419528,
        "gs_name": "BxL_Chr1QTL",
        "gs_abbreviation": "BxL_Chr1QTL",
        "pub_id": None,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "Set of genes underlying QTL peak on Chr 1 from a cross "
        + "between C57BL/6J and LG/J",
        "sp_id": 1,
        "gs_count": 476,
        "gs_threshold_type": 1,
        "gs_threshold": 0.5,
        "gs_groups": -1,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -7,
        "gs_created": "2019-01-07",
        "admin_flag": None,
        "gs_updated": "2019-01-07 16:44:44.871811",
        "gs_status": "deleted",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 225459,
        "usr_id": 7605962,
        "file_id": 279397,
        "gs_name": "10 ProbeSets imported from Genenetwork",
        "gs_abbreviation": "import from Genenetwork",
        "pub_id": None,
        "res_id": None,
        "cur_id": None,
        "gs_description": "10 ProbeSets imported from Genenetwork",
        "sp_id": 2,
        "gs_count": 1,
        "gs_threshold_type": 3,
        "gs_threshold": 0.5,
        "gs_groups": None,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -1,
        "gs_created": None,
        "admin_flag": None,
        "gs_updated": "2015-07-21 08:56:24.109389",
        "gs_status": "normal",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 225460,
        "usr_id": 7605962,
        "file_id": 279398,
        "gs_name": "10 ProbeSets imported from Genenetwork",
        "gs_abbreviation": "import from Genenetwork",
        "pub_id": None,
        "res_id": None,
        "cur_id": None,
        "gs_description": "10 ProbeSets imported from Genenetwork",
        "sp_id": 2,
        "gs_count": 1,
        "gs_threshold_type": 3,
        "gs_threshold": 0.5,
        "gs_groups": None,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -1,
        "gs_created": None,
        "admin_flag": None,
        "gs_updated": "2015-07-21 09:07:59.646405",
        "gs_status": "normal",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 355159,
        "usr_id": 420,
        "file_id": 418906,
        "gs_name": "bleh",
        "gs_abbreviation": "bleh",
        "pub_id": 78799,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "bleh",
        "sp_id": 1,
        "gs_count": 0,
        "gs_threshold_type": None,
        "gs_threshold": None,
        "gs_groups": 195,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": 0,
        "gs_created": "2018-09-05",
        "admin_flag": None,
        "gs_updated": "2018-09-05 11:30:34.455506",
        "gs_status": "delayed",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 355820,
        "usr_id": 563,
        "file_id": 419526,
        "gs_name": "Chr1QTL_BxL",
        "gs_abbreviation": "Chr1QTL",
        "pub_id": None,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "Candidate Genes under QTL interval",
        "sp_id": 1,
        "gs_count": 601,
        "gs_threshold_type": 1,
        "gs_threshold": 0.5,
        "gs_groups": -1,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -2,
        "gs_created": "2019-01-04",
        "admin_flag": None,
        "gs_updated": "2019-01-04 22:10:26.44613",
        "gs_status": "deleted",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 357555,
        "usr_id": 12364375,
        "file_id": 421263,
        "gs_name": "Habenular TCF7L2 links nicotine addiction to diabetes",
        "gs_abbreviation": "Nicotine addiction linked with diabetes",
        "pub_id": 78944,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "Nicotine addiction linked with diabetes in rats",
        "sp_id": 3,
        "gs_count": 0,
        "gs_threshold_type": None,
        "gs_threshold": None,
        "gs_groups": 364,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": 0,
        "gs_created": "2020-01-23",
        "admin_flag": None,
        "gs_updated": "2020-01-23 21:01:19.721293",
        "gs_status": "delayed",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 355821,
        "usr_id": 563,
        "file_id": 419527,
        "gs_name": "Chr1QTL_BxL",
        "gs_abbreviation": "Chr1QTL",
        "pub_id": None,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "Candidate Genes under QTL interval",
        "sp_id": 1,
        "gs_count": 601,
        "gs_threshold_type": 1,
        "gs_threshold": 0.5,
        "gs_groups": -1,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -4,
        "gs_created": "2019-01-04",
        "admin_flag": None,
        "gs_updated": "2019-01-07 09:35:16.859779",
        "gs_status": "deleted",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 278976,
        "usr_id": 10328349,
        "file_id": 342490,
        "gs_name": "real DO anxiety correlations",
        "gs_abbreviation": "real",
        "pub_id": None,
        "res_id": None,
        "cur_id": 5,
        "gs_description": "testing",
        "sp_id": 1,
        "gs_count": 377,
        "gs_threshold_type": 3,
        "gs_threshold": 0.5,
        "gs_groups": -1,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -2,
        "gs_created": "2018-01-03",
        "admin_flag": None,
        "gs_updated": "2018-02-23 12:22:39.342697",
        "gs_status": "deleted",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": "f",
    },
    {
        "gs_id": 128638,
        "usr_id": 4686,
        "file_id": 140583,
        "gs_name": "Copy Number Variations effecting Alcoholism in Korean Population",
        "gs_abbreviation": "CNVs Alcoholism Korean Pop",
        "pub_id": 645,
        "res_id": None,
        "cur_id": 1,
        "gs_description": (
            "Table 2. Logistic Regression Analysis of Identified "
            + "Common CNV Regions (Frequency >0.01) with Risk of "
            + "Alcoholism in Korean Subject (n=1,138)"
        ),
        "sp_id": 2,
        "gs_count": 14,
        "gs_threshold_type": 3,
        "gs_threshold": 0.5,
        "gs_groups": 0,
        "gs_attribution_old": None,
        "gs_uri": None,
        "gs_gene_id_type": -7,
        "_searchtext": (
            "'0.01':20B '1':29B '138':30B '2':10B 'alcohol':5A,24B "
            + "'analysi':13B 'cnv':17B 'common':16B 'copi':1A 'effect':4A "
            + "'frequenc':19B 'identifi':15B 'korean':7A,26B 'logist':11B "
            + "'n':28B 'number':2A 'popul':8A 'region':18B 'regress':12B "
            + "'risk':22B 'subject':27B 'tabl':9B 'variat':3A"
        ),
        "gs_created": None,
        "admin_flag": None,
        "gs_updated": "2020-05-06 09:19:44.883323",
        "gs_status": "normal",
        "gsv_qual": {},
        "_comments_author": None,
        "_comments_curator": None,
        "gs_attribution": None,
        "gs_is_edgelist": False,
    },
]


GENESET_HOM_IDS = [
    48535,
    55864,
    8034,
    74393,
    4611,
    110643,
    50955,
    12033,
    54768,
    115686,
    14738,
    37666,
    1986,
    3210,
    41891,
    28185,
    137316,
    20906,
    10314,
    8213,
    129842,
    7710,
    9037,
    8352,
    8849,
    23587,
    4783,
    11048,
    86729,
    5518,
    8077,
    9858,
    20970,
    11906,
    2645,
    8250,
    3975,
    3980,
    12203,
    18328,
    69237,
    9410,
    32141,
    12089,
    37987,
    18182,
    107175,
    35065,
    15019,
    23416,
    55547,
    21383,
    5940,
    10234,
    21173,
    9151,
    134516,
    7297,
    47925,
    68303,
    10044,
    3263,
    37926,
    14632,
    2318,
    5162,
    6081,
    8227,
    14289,
    2506,
    38035,
    210,
    3835,
    10127,
    6981,
    5057,
    20498,
    19061,
    5238,
    22278,
    17799,
    115929,
    3630,
    10959,
    10173,
    18874,
    5652,
    17139,
    2106,
    22815,
    3124,
]
